export const categories = [
  {
    id: 0,
    img: "/images/t-shirt-1.png",
    title: "T-SHIRTS",
    desc: "In cheap price, various kinds, several sizes, best qualities and fashion ",
    fav: 5,
    priceHint: "starting from $15",
  },
  {
    id: 1,
    img: "/skirt-1.jpg",
    title: "SKIRTS",
    desc: "In cheap price, various kinds, several sizes, best qualities and fashion ",
    fav: 12,
    priceHint: "starting from $25",
  },
  {
    id: 2,
    img: "/images/shoes-1.jpg",
    title: "SHOES",
    desc: "In cheap price, various kinds, several sizes, best qualities and fashion ",
    fav: 33,
    priceHint: "starting from $35",
  },
  {
    id: 3,
    img: "/jacket-1.jpg",
    title: "JACKET",
    desc: "In cheap price, various colors, several sizes, best qualities and fashion ",
    fav: 109,
    priceHint: "starting from $42",
  },
  {
    id: 4,
    img: "/images/perfume-1.jpg",
    title: "PERFUME",
    desc: "In cheap price, various kinds, attractive odors, best qualities and fashion ",
    fav: 18,
    priceHint: "starting from $12",
  },
  {
    id: 5,
    img: "/images/jewlery-1.jpg",
    title: "JEWLERY",
    desc: "In cheap price, various DESIGNS, several sizes, best qualities and fashion ",
    fav: 312,
    priceHint: "starting from $2",
  },
  {
    id: 6,
    img: "/watch-1.jpg",
    title: "WATCHES",
    desc: "In cheap price, various colors, several sizes, best qualities and fashion ",
    fav: 2,
    priceHint: "starting from $7",
  },
];
