export const categories = [
  {
    id: 0,
    img: "/images/t-shirt-1.png",
    title: "T-SHIRTS",
    desc: "In cheap price, various kinds, several sizes, best qualities and fashion ",
    fav: 5,
    priceHint: "Starting from $15",
  },
  {
    id: 1,
    img: "/skirt-1.jpg",
    title: "SKIRTS",
    desc: "In cheap price, various kinds, several sizes, best qualities and fashion ",
    fav: 12,
    priceHint: "Starting from $25",
  },
  {
    id: 2,
    img: "/images/shoes-1.jpg",
    title: "SHOES",
    desc: "In cheap price, various kinds, several sizes, best qualities and fashion ",
    fav: 33,
    priceHint: "Starting from $35",
  },
  {
    id: 3,
    img: "/jacket-1.jpg",
    title: "JACKET",
    desc: "In cheap price, various colors, several sizes, best qualities and fashion ",
    fav: 109,
    priceHint: "Starting from $42",
  },
  {
    id: 4,
    img: "/images/perfume-1.jpg",
    title: "PERFUME",
    desc: "In cheap price, various kinds, attractive odors, best qualities and fashion ",
    fav: 18,
    priceHint: "Starting from $12",
  },
  {
    id: 5,
    img: "/images/jewlery-1.jpg",
    title: "JEWLERY",
    desc: "In cheap price, various DESIGNS, several sizes, best qualities and fashion ",
    fav: 312,
    priceHint: "Starting from $2",
  },
  {
    id: 6,
    img: "/watch-1.jpg",
    title: "WATCHES",
    desc: "In cheap price, various colors, several sizes, best qualities and fashion ",
    fav: 2,
    priceHint: "Starting from $7",
  },
  {
    id: 7,
    img: "/sports-1.jpg",
    title: "SPORTS",
    desc: "In cheap price, various kinds, several sizes, best qualities and fashion ",
    fav: 15,
    priceHint: "Starting from $17",
  },
  {
    id: 8,
    img: "/images/alarm-clock-11.jpg",
    title: "ALARM CLOCK",
    desc: "In cheap price, various styles, several sizes, best qualities and fashion ",
    fav: 22,
    priceHint: "Starting from $19",
  },
  {
    id: 9,
    img: "/images/blouse-1.jpg",
    title: "BLOUSE / SHIRT",
    desc: "In cheap price, various colors, several sizes, best qualities and fashion ",
    fav: 11,
    priceHint: "Starting from $27",
  },
  {
    id: 10,
    img: "/images/tie-1.png",
    title: "TIE FOR MEN",
    desc: "In cheap price, various colors, several sizes, best qualities and fashion ",
    fav: 20,
    priceHint: "Starting from $3",
  },
];
export const Incomingcategories = [
  {
    id: 0,
    img: "/images/jeans-1.jpg",
    title: "JEANS TROUSERS",
    desc: "In cheap price, various brans, several sizes, best qualities and fashion ",
    fav: 15,
    priceHint: "Starting from $50",
  },
  {
    id: 1,
    img: "/images/hair-1.jpeg",
    title: "HUMAN HAIR",
    desc: "In cheap price, various brands, several colors, best qualities and fashion ",
    fav: 12,
    priceHint: "Starting from $25",
  },
  {
    id: 2,
    img: "/images/shoes-1.jpg",
    title: "SHOES",
    desc: "In cheap price, various kinds, several sizes, best qualities and fashion ",
    fav: 33,
    priceHint: "Starting from $35",
  },
  {
    id: 3,
    img: "/jacket-1.jpg",
    title: "JACKET",
    desc: "In cheap price, various colors, several sizes, best qualities and fashion ",
    fav: 109,
    priceHint: "Starting from $42",
  },
  {
    id: 4,
    img: "/images/perfume-1.jpg",
    title: "PERFUME",
    desc: "In cheap price, various kinds, attractive odors, best qualities and fashion ",
    fav: 18,
    priceHint: "Starting from $12",
  },
  {
    id: 5,
    img: "/images/jewlery-1.jpg",
    title: "JEWLERY",
    desc: "In cheap price, various DESIGNS, several sizes, best qualities and fashion ",
    fav: 312,
    priceHint: "Starting from $2",
  },
];

export const frequentlyOrdered = [
  {
    id: 0,
    img: "/watch-1.jpg",
    title: "WATCHES",
    desc: "In cheap price, various colors, several sizes, best qualities and fashion ",
    fav: 2,
    priceHint: "Starting from $7",
  },
  {
    id: 1,
    img: "/sports-1.jpg",
    title: "SPORTS",
    desc: "In cheap price, various kinds, several sizes, best qualities and fashion ",
    fav: 15,
    priceHint: "Starting from $17",
  },
  {
    id: 2,
    img: "/images/alarm-clock-11.jpg",
    title: "ALARM CLOCK",
    desc: "In cheap price, various styles, several sizes, best qualities and fashion ",
    fav: 22,
    priceHint: "Starting from $19",
  },
  {
    id: 3,
    img: "/images/blouse-1.jpg",
    title: "BLOUSE / SHIRT",
    desc: "In cheap price, various colors, several sizes, best qualities and fashion ",
    fav: 11,
    priceHint: "Starting from $27",
  },
  {
    id: 4,
    img: "/images/tie-1.png",
    title: "TIE FOR MEN",
    desc: "In cheap price, various colors, several sizes, best qualities and fashion ",
    fav: 20,
    priceHint: "Starting from $3",
  },
];

export const recentlyAdded = [
  {
    id: 0,
    img: "/images/perfume-1.jpg",
    title: "PERFUME",
    desc: "In cheap price, various kinds, attractive odors, best qualities and fashion ",
    fav: 18,
    priceHint: "Starting from $12",
  },
  {
    id: 1,
    img: "/images/alarm-clock-11.jpg",
    title: "ALARM CLOCK",
    desc: "In cheap price, various styles, several sizes, best qualities and fashion ",
    fav: 22,
    priceHint: "Starting from $19",
  },
  {
    id: 2,
    img: "/images/blouse-1.jpg",
    title: "BLOUSE / SHIRT",
    desc: "In cheap price, various colors, several sizes, best qualities and fashion ",
    fav: 11,
    priceHint: "Starting from $27",
  },
];
export const categoriesWithDiscount = [
  {
    id: 0,
    img: "/watch-1.jpg",
    title: "WATCHES",
    desc: "In cheap price, various colors, several sizes, best qualities and fashion ",
    fav: 2,
    priceHint: "Starting from $7 with 10-20% discount",
    discount: "10-30",
  },
  {
    id: 1,
    img: "/sports-1.jpg",
    title: "SPORTS",
    desc: "In cheap price, various kinds, several sizes, best qualities and fashion ",
    fav: 15,
    priceHint: "Starting from $17",
    discount: "30-45",
  },
  {
    id: 2,
    img: "/images/alarm-clock-11.jpg",
    title: "ALARM CLOCK",
    desc: "In cheap price, various styles, several sizes, best qualities and fashion ",
    fav: 22,
    priceHint: "Starting from $19",
    discount: "5-13",
  },
  {
    id: 3,
    img: "/images/blouse-1.jpg",
    title: "BLOUSE / SHIRT",
    desc: "In cheap price, various colors, several sizes, best qualities and fashion ",
    fav: 11,
    priceHint: "Starting from $27",
    discount: "50",
  },
];
